[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "BetterMissions"
versionNumber = "1.0.1"
description = "An VRising mod to do a better control of the servant missions."
websiteUrl = "https://github.com/caioreix/BetterMissions"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
deca-Bloodstone = "0.1.4"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = []
