[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "BetterMissions"
versionNumber = "0.0.0"
description = "A VRising mod to do a better control of the servant missions giving players options to change mission settings."
websiteUrl = "https://github.com/caioreix/BetterMissions"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = ["Client", "Server", "Oakveil Update"]
